# @package _global_

dset:
  segment: 11
  sources: ['drums', 'bass', 'other', 'vocals']
  shift: 0

test:
  every: 1

epochs: 20

save_every: 1
weights: [1., 0., 0., 0.]

misc:
  #show: true
  verbose: true
  num_workers: 0

augment:
  shift_same: false
  repitch:
    proba: false
  remix:
    proba: false
  scale:
    proba: false
  flip: false

model: demucs

batch_size: 4

logs:
    interval: 10
    level: info