# @package _global_

dset:
  segment: 11
  sources: ['drums', 'bass', 'other', 'vocals']
  shift: 0

test:
  every: 10

epochs: 10

save_every: 1
weights: [1., 0., 0., 0.]

misc:
  #show: true
  num_workers: 0

augment:
  shift_same: false
  repitch:
    proba: 0.1
  remix:
    proba: false
  scale:
    proba: 1
  flip: false

model: drumamba

batch_size: 4


drumamba:
  mamba_layers: 0
  res_mamba_mode: 3
  res_mamba_start: 3