# @package _global_

dset:
  segment: 11
  sources: ['drums', 'bass', 'other', 'vocals']
  shift: 0

test:
  every: 10
  save: True
  sdr: True

epochs: 30

save_every: 5
weights: [1., 0., 0., 0.]

misc:
  #show: true
  num_workers: 0

augment:
  shift_same: false
  repitch:
    proba: 0.1
  remix:
    proba: false
  scale:
    proba: 1
  flip: false

model: drumamba

batch_size: 2


drumamba:
  mamba_layers: 0
  comp_res_mode: 3
  comp_res_start: 1