# @package _global_

dset:
  musdb: ./datasets/simple
  segment: 11
  sources: ['drums', 'bass', 'other', 'vocals']
  shift: 0

test:
  every: 1

epochs: 10

save_every: 10
weights: [1., 0., 0., 0.]

misc:
  #show: true
  num_workers: 0

augment:
  shift_same: false
  repitch:
    proba: false
  remix:
    proba: false
  scale:
    proba: false
  flip: false

model: demucs

batch_size: 4


demucs:
  kernel_size: 16
  stride: 8
  dconv_mode: 1
  dconv_comp: 10
  dconv_attn: 10
  dconv_lstm: 10